apiVersion: v1
kind: Secret
metadata:
  name: guitarstore-secret
  namespace: guitarstore
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-k8s-secret-key-change-in-production"
  DB_PASSWORD: "123"
